server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://10.1.13.164:8050/eureka/
#框架整合相关配置
spring:
  #该服务在注册中心中的名字
  application:
    name: zuul-server
#自定义的路径映射
zuul:
  routes:
    goods-server: /gateway/**
  #过滤
  ignored-patterns: /*-server/**
  host:
    connect-timeout-millis: 10000 #HTTP连接超时要比Hystrix的大
    socket-timeout-millis: 50000   #socket超时
  #限流配置
  ratelimit:
    key-prefix: springcloud-ratelimit #按粒度拆分的临时变量key前缀
    enabled: true #启用开关
    repository: REDIS #key存储，默认是IN_MEMORY本地内存，此外还有多种形式
    behind-proxy: true #表示代理之后
    default-policy: #全局限流策略，可单独细化到服务粒度
      limit: 20 #在一个单位时间窗口的请求数量
      quota: 1 #在一个单位时间窗口的请求时间限制
      refresh-interval: 5 #单位时间窗口
      type: url #可指定url粒度
    policies: #针对于不同服务的限流策略
      point-server: #针对于积分服务
        limit: 2
        quota: 1
        refresh-interval: 5
        type: url
